site_name: Cluster HPC
site_description: Documentação do Cluster de Computação
site_author: Equipe de Infraestrutura
site_url: https://darlon.github.io/clusterina/

theme:
  name: material
  language: pt-BR

nav:
  - Início: index.md
  - Arquitetura: arquitetura.md
  - Solicitar Acesso: solicitar-acesso.md
  - Como utilizar: como-utilizar.md
  - Grupos de Pesquisa: grupos-pesquisa.md
